### PR TITLE
ENH: added discussion of python community standards

### PR DESCRIPTION
**Pull request by gregcaporaso**
This replaces my previous pull request (#894), and addresses all of @arokem's comments on that pull request.

### CODE REVIEW

**Comment by gregcaporaso** [comment]
@gvwilson, do you need anything else on this one? No problem if you just haven't had time to review yet, just wanted to check in on status.

**Comment by gvwilson** [comment]
Hi @gregcaporaso,
Sorry, this one fell off the side - @abostroem, can you please review?
Thanks 
Greg

**Comment by gregcaporaso** [comment]
No problem, thanks!

**Comment by gvwilson** [comment]
Relocated to https://github.com/swcarpentry/python-novice-gapminder/issues/14

**Pull request closed without merging**
