### PR TITLE
added section on python community standards

### PR DESCRIPTION
**Pull request by gregcaporaso**
Submitted as part of my final assignment for the *Instructor training 11* course. 

I think this is very useful information for new python developers, to make them aware of these types of coding and documentation standards as they begin developing their own software. Even if students don't end up being python developers, it's useful for them to know that these types of standards exist so they can try to track them down for their programming language of choice. 

If you agree that this is useful information to include in the lessons, I'm happy to relocate, expand/reduce, etc to make it fit best with the existing lessons.

### CODE REVIEW

**Comment by gregcaporaso** [comment]
My last push addresses all of @arokem's comments, and merges master. I'm not sure why all of files are showing up as updated in this PR though - my only changes were to ``novice/ref/03-python.md``. 

@gvwilson, do you want me to close this pull request and open another that contains only the changes in ``novice/ref/03-python.md``?

**Comment by gvwilson** [comment]
> @gvwilson <https://github.com/gvwilson>, do you want me to close this 
> pull request and open another that contains only the changes in 
> |novice/ref/03-python.md|?
Yes please.

**Comment by arokem** [comment]
:+1:

**Comment by gregcaporaso** [comment]
closed in favor of #930

**Pull request closed without merging**
